<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IITMSPC75" failures="1" tests="6" name="Default test" time="0.071" errors="0" timestamp="2023-04-07T17:09:30 IST">
  <testcase classname="academicui.SKIPTHETEST" name="atest2R" time="0.011"/>
  <testcase classname="academicui.SKIPTHETEST" name="btest1" time="0.002"/>
  <testcase classname="academicui.SKIPTHETEST" name="btest3" time="0.002"/>
  <testcase classname="academicui.SKIPTHETEST" name="btest4" time="0.001">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	Syntax error on token &amp;quot;throw&amp;quot;, delete this token
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Syntax error on token "throw", delete this token

at academicui.SKIPTHETEST.btest4(SKIPTHETEST.java:58)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- btest4 -->
  <testcase classname="academicui.SKIPTHETEST" name="atest1R" time="0.001"/>
  <testcase classname="academicui.SKIPTHETEST" name="btest2" time="0.002"/>
</testsuite> <!-- Default test -->
